// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace TestingDrive
{
    public partial class ProfanityChecker
    {
        /// <summary>
        /// model input class for ProfanityChecker.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"worker_id")]
            public string Worker_id { get; set; }

            [ColumnName(@"task_id")]
            public string Task_id { get; set; }

            [ColumnName(@"task_response_id")]
            public string Task_response_id { get; set; }

            [ColumnName(@"text")]
            public string Text { get; set; }

            [ColumnName(@"Is this text toxic?")]
            public string Is_this_text_toxic_ { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ProfanityChecker.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"worker_id")]
            public string Worker_id { get; set; }

            [ColumnName(@"task_id")]
            public string Task_id { get; set; }

            [ColumnName(@"task_response_id")]
            public string Task_response_id { get; set; }

            [ColumnName(@"text")]
            public float[] Text { get; set; }

            [ColumnName(@"Is this text toxic?")]
            public uint Is_this_text_toxic_ { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ProfanityChecker.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
