
// This file was auto-generated by ML.NET Model Builder. 

using ProfanityChecker_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
ProfanityChecker.ModelInput sampleData = new ProfanityChecker.ModelInput()
{
    Text = @"Thank you :)",
};

// Make a single prediction on the sample data and print results
var predictionResult = ProfanityChecker.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Is_this_text_toxic_ with predicted Is_this_text_toxic_ from sample data...\n\n");


Console.WriteLine($"Text: {@"Thank you :)"}");
Console.WriteLine($"Is_this_text_toxic_: {@"Not Toxic"}");


Console.WriteLine($"\n\nPredicted Is_this_text_toxic_: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

